package Visao;
import java.awt.event.ActionListener;
import javax.swing.table.TableModel;

public class TelaAgenda extends javax.swing.JFrame {

    /** Creates new form FrameAgenda */
    public TelaAgenda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtAgenda = new javax.swing.JTable();
        jbAdicionar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbListar = new javax.swing.JButton();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda Telefonica");

        jScrollPane1.setViewportView(jtAgenda);

        jbAdicionar.setText("Adicionar");
        jbAdicionar.setToolTipText("Adiciona um contato à lista");

        jbEditar.setText("Editar");
        jbEditar.setToolTipText("Editar o contato selecionado da lista");

        jbExcluir.setText("Excluir");
        jbExcluir.setToolTipText("Excluir o contato selecionado da lista");
        
        jbListar.setText("Listar");
        jbListar.setToolTipText("Listar os contatos");
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addComponent(jbListar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdicionar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbListar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    public void setJtAgendaModel(TableModel modelo) {
        jtAgenda.setModel(modelo);
    }
    
    public int getLinhaSelecionada() {
        return jtAgenda.getSelectedRow();
    }
    

    public void addActionListener(ActionListener listener) {
        jbAdicionar.addActionListener(listener);
        jbEditar.addActionListener(listener);
        jbExcluir.addActionListener(listener);
        jbListar.addActionListener(listener);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTable jtAgenda;
    private javax.swing.JButton jbListar;
    // End of variables declaration//GEN-END:variables

}